-- FK's --
ALTER TABLE DB_ANSWER ADD CONSTRAINT FK_ANSWER_OPTION FOREIGN KEY (Id_Answer_Option) REFERENCES DB_ANSWER_OPTIONS(Id);
ALTER TABLE DB_ANSWER ADD CONSTRAINT FK_ANSWER_TOPIC FOREIGN KEY (Id_Topic) REFERENCES DB_TOPICS(Id);
ALTER TABLE DB_ANSWER ADD CONSTRAINT FK_ANSWER_QUESTION FOREIGN KEY (Id_Question) REFERENCES DB_QUESTIONS(Id);
ALTER TABLE DB_ANSWER ADD CONSTRAINT FK_ANSWER_SURVEY FOREIGN KEY (Id_Survey) REFERENCES DB_SURVEY(Id);


-- Delete FK
ALTER TABLE DB_ANSWER DROP CONSTRAINT FK_ANSWER_OPTION;
ALTER TABLE DB_ANSWER DROP CONSTRAINT FK_ANSWER_TOPIC;
ALTER TABLE DB_ANSWER DROP CONSTRAINT FK_ANSWER_QUESTION;
ALTER TABLE DB_ANSWER DROP CONSTRAINT FK_ANSWER_SURVEY;
