-- FK's --
ALTER TABLE DB_QUESTIONS ADD CONSTRAINT FK_QUESTION_SURVEY FOREIGN KEY (Id_Survey) REFERENCES DB_SURVEY(Id);

ALTER TABLE DB_TOPICS ADD CONSTRAINT FK_TOPIC_QUESTION FOREIGN KEY (Id_Question) REFERENCES DB_QUESTIONS(Id);

ALTER TABLE DB_ANSWER ADD CONSTRAINT FK_ANSWER_TOPIC FOREIGN KEY (Id_Topic) REFERENCES DB_TOPICS(Id);
ALTER TABLE DB_ANSWER ADD CONSTRAINT FK_ANSWER_QUESTION FOREIGN KEY (Id_Question) REFERENCES DB_QUESTIONS(Id);
ALTER TABLE DB_ANSWER ADD CONSTRAINT FK_ANSWER_SURVEY FOREIGN KEY (Id_Survey) REFERENCES DB_SURVEY(Id);


-- Delete FK
ALTER TABLE DB_QUESTIONS DROP CONSTRAINT FK_QUESTION_SURVEY;

ALTER TABLE DB_TOPICS DROP CONSTRAINT FK_TOPIC_QUESTION;

ALTER TABLE DB_ANSWER DROP CONSTRAINT FK_ANSWER_TOPIC;
ALTER TABLE DB_ANSWER DROP CONSTRAINT FK_ANSWER_QUESTION;
ALTER TABLE DB_ANSWER DROP CONSTRAINT FK_ANSWER_SURVEY;